name: Release and Deploy

on:
  release:
    types: [created]
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write  # Needed for uploading release assets
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Wasm/JS application
        run: |
          ./gradlew composeApp:wasmJsBrowserProductionWebpack

      - name: Build desktop application
        run: |
          ./gradlew composeApp:packageReleaseUberJarForCurrentOS
          ./gradlew composeApp:packageReleaseDmg
          ./gradlew composeApp:packageReleaseExe
          ./gradlew composeApp:packageReleaseMsi
          ./gradlew composeApp:packageReleaseAppImage
          ./gradlew composeApp:packageReleaseInternal

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./composeApp/build/compose/binaries/main-release/msi/*.msi
            ./composeApp/build/compose/binaries/main-release/exe/*.exe
            ./composeApp/build/compose/binaries/main-release/dmg/*.dmg
            ./composeApp/build/compose/binaries/main-release/appimage/*.AppImage
            ./composeApp/build/compose/binaries/main-release/deb/*.deb

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './composeApp/build/dist/wasmJs/productionExecutable'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
